<?php
namespace frontend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\Article;
use yii\web\Response;

/**
 * Site controller
 */
class ArticleController extends Controller
{
    /*public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }*/

    public function actionOne()
    {
        //var_dump(1223);die;
        $article = new Article();
        $article->id = Yii::$app->request->post('id');
        return json_encode( $article->getOne());
    }
}