<?php
namespace frontend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\Article;
use yii\web\Response;

/**
 * Site controller
 */
class ArticleController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionOne()
    {
        $article = new Article();
        $article->id = Yii::$app->request->post('id');
        return $article->getOne();
    }
    public function actionList()
    {
        $article = new Article();
        $article->status = 1;
        $article->id = Yii::$app->request->post('id');
        list($total, $result) = $article->getList();
        return $result;
    }
}