<?php
namespace frontend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\Comment;
use yii\web\Response;

/**
 * Site controller
 */
class CommentController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionAdd()
    {
        $comment = new Comment();
        $comment->id = Yii::$app->request->post('id');
        var_dump(Yii::$app->request->post());die;
        return $comment->getAdd();
    }

}