<?php
namespace frontend\controllers\api;

use common\models\File;
use Yii;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class FileController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionUrl()
    {
        $file = new File();
        $file->name = Yii::$app->request->post('name');
        //var_dump(Yii::$app->request->post() , $file);die;
        return $file->FileUrl();
    }

}