<?php
namespace frontend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\UploadImg;
use yii\web\Response;

/**
 * Site controller
 */
class ImgController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionCreate()
    {
        $uploadImg = new UploadImg();
        $uploadImg->id = Yii::$app->request->post();
        return $uploadImg->getCreate();
    }
    public function actionOne()
    {
        $uploadImg = new UploadImg();
        $uploadImg->id = Yii::$app->request->post('id');
        return $uploadImg->getOne();
    }
    public function actionList()
    {
        $uploadImg = new UploadImg();
        $uploadImg->status = 1;
        $uploadImg->id = Yii::$app->request->post('id');
        list($total, $result) = $uploadImg->getList();
        return $result;
    }
}