<?php
namespace backend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\ClassRoom;
use yii\web\Response;
use common\models\User;
use common\models\Alumna;

/**
 * Site controller
 */
class AlumnaController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
    public function actionList()
    {
        $classRoom = new Alumna();
        $classRoom->scenario = Alumna::SCENARIO_LIST;
        $classRoom->setAttributes(Yii::$app->request->post());
        $classRoom->expand = ['user'];
        list($total, $result) = $classRoom->getList();
        return ['data'=>$result , 'total' => $total];
    }
    public function actionEdit()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_EDIT;
        $classRoom->setAttributes(Yii::$app->request->post());
        return $classRoom->getEdit();
    }
    public function actionUpdate()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_UPDATE;
        $postData = Yii::$app->request->post();
        $classRoom->setAttributes($this->SafeFilter($postData));
        return $classRoom->getUpdate();
    }
    public function actionAdd()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_ADD;
        $postData = Yii::$app->request->post();
        $classRoom->setAttributes($this->SafeFilter($postData));
        return $classRoom->getAdd();

    }
}