<?php
namespace backend\controllers\api;


use Yii;
use yii\web\Controller;
use common\models\ClassRoom;
use yii\web\Response;
use common\models\User;

/**
 * Site controller
 */
class ClassRoomController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionOne()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_ADD;
        $classRoom->id = Yii::$app->request->post('id');
        return $classRoom->getOne();
    }
    public function actionData()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_ADD;
        $classRoom->order_by = ['id'=>2];
        $classRoom =  $classRoom->getOne();

        $user = new User();
        $user->expand = ['teacher'];
        $user->type = 2;
        list($total, $user) = $user->getList();
        return [
            'number' => $classRoom,
            'user' => $user
        ];
    }
    public function actionList()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_LIST;
        $classRoom->setAttributes(Yii::$app->request->post());
        $classRoom->expand = ['user'];
        list($total, $result) = $classRoom->getList();
        foreach($result as &$item){
            if($item['maintain']){
                $item['maintain'] = json_decode($item['maintain']);
            }
        }
        return ['data'=>$result , 'total' => $total];
    }
    public function actionEdit()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_EDIT;
        $classRoom->setAttributes(Yii::$app->request->post());
        return $classRoom->getEdit();
    }
    public function actionUpdate()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_UPDATE;
        $postData = Yii::$app->request->post();
        $classRoom->setAttributes($this->SafeFilter($postData));
        return $classRoom->getUpdate();
    }
    public function actionAdd()
    {
        $classRoom = new ClassRoom();
        $classRoom->scenario = ClassRoom::SCENARIO_ADD;
        $postData = Yii::$app->request->post();
        $classRoom->setAttributes($this->SafeFilter($postData));
        return $classRoom->getAdd();

    }
}