<?php
namespace backend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\User;
use yii\web\Response;
use common\models\Department;
use common\models\Major;
use common\models\Course;
use common\models\UserTeacher;
use common\models\UserStudent;

/**
 * Site controller
 */
class CourseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
    public function actionData()
    {
        $department_id = Yii::$app->request->post('department_id');
        $major = new Major();
        $major->department_id = $department_id;
        list($total , $major) = $major->getList();

        $user = new UserTeacher();
        $user->department_id = $department_id;
        $user->expand = ['user'];
        list($total , $user) = $user->getList();

        return[
            'major' => $major,
            'user' => $user,
        ];
    }
    public function actionList()
    {
        $course = new Course();
        $course->scenario = Course::SCENARIO_LIST;
        $course->setAttributes(Yii::$app->request->post());
        $course->expand = ['user' , 'major' , 'department','classRoom'];
        list($total, $result) = $course->getList();
        if($result){
            foreach($result as &$value){
                $value['people'] = 0;//UserStudent::find()->where(['team_id'=>$value['id']])->count();
            }
        }
        return ['data'=>$result , 'total' => $total];
    }
    public function actionListData()
    {
        $user = new User();
        $user->type = [1,2];
        $user->expand = ['student' , 'teacher'];
        $user->per_page = '';
        list($totle , $user) = $user->getList();
        $student = [];$teacher = [];
        foreach($user as $value){
            if($value['type'] == 1){
                $student[] = $value;
            }elseif($value['type'] == 2){
                $teacher[] = $value;
            }
        }
        $major = new Major();
        $major->per_page = '';
        list($total, $major) = $major->getList();

        $department = new Department();
        $department->per_page = '';
        list($total, $department) = $department->getList();
        return[
            'student' => $student,
            'teacher' => $teacher,
            'major' => $major,
            'department' => $department,
        ];
    }
    public function actionEdit()
    {
        $course = new Course();
        $course->scenario = Course::SCENARIO_EDIT;
        $course->setAttributes(Yii::$app->request->post());
        return $course->getEdit();
    }
    public function actionAdd()
    {
        $course = new Course();
        $course->scenario = Course::SCENARIO_ADD;
        $course->setAttributes(Yii::$app->request->post());
        return $course->getAdd();
    }
}