<?php
namespace backend\controllers\api;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use common\models\UserTeacher;
use common\models\Alumna;
use common\models\Department;
use common\models\Register;
use common\models\UserStudent;

/**
 * Site controller
 */
class DashboardController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionTodo()
    {
        $student = new UserStudent();
        list($stuTotal , $student) = $student->getList();
        $teacher = new UserTeacher();
        list($teaTotal , $teacher) = $teacher->getList();
        $department = new Department();
        list($depTotal , $department) = $department->getList();
        $alumna = new Alumna();
        list($aiuTotal , $alumna) = $alumna->getList();
        $overCount = [];
        $overCount['studentList'] = $stuTotal;
        $overCount['teacherList'] = $teaTotal;
        $overCount['departmentList'] = $depTotal;
        $overCount['alumnaList'] = $aiuTotal;
        $stuStatus = [];$teaStatus = [];
        $newStudent=[];
        $newStudent[date('Y')] = 0;
        $newStudent[date('Y')-1] = 0;
        $newStudent[date('Y')-2] = 0;
        $newStudent[date('Y')-3] = 0;
        if($student){
            foreach($student as $value){
                $stuStatus[$value['status']] = isset($stuStatus[$value['status']]) ? $stuStatus[$value['status']]+= 1 : 1;
                if(date('Y' , $value['create_time']) == date('Y')){
                    $newStudent[date('Y')] = ++$newStudent[date('Y')];
                }
                if(date('Y' , $value['create_time']) == (date('Y')-1)){
                    $newStudent[date('Y')-1] = ++$newStudent[date('Y')-1];
                }
                if(date('Y' , $value['create_time']) == (date('Y')-2)){
                    $newStudent[date('Y')-2] = ++$newStudent[date('Y')-2];
                }
                if(date('Y' , $value['create_time']) == (date('Y')-3)){
                    $newStudent[date('Y')-3] = ++$newStudent[date('Y')];
                }
            }
        }
        if($teacher){
            foreach($teacher as $value){
                $teaStatus[$value['division_id']] = isset($teaStatus[$value['division_id']]) ? $teaStatus[$value['division_id']]+= 1 : 1;
            }
        }
        $register = new Register();
        $register->setAttributes(Yii::$app->request->post());
        $register->expand = ['student.user'];
        list($registerCount , $register) = $register->getList();
        $course = [];
        if($register){
            foreach($register as $value){
                if($value['score']>=60) {
                    $course['pass'] = isset($course['pass'])? $course['pass'] += 1 : 1 ;
                }
                if($value['score']>=85) {
                    $course['super'] = isset($course['super'])? $course['super'] += 1 : 1 ;
                }
            }
            $course['pass'] = round($course['pass']/$registerCount*100 , 2);
            $course['super'] = round($course['super']/$registerCount*100 , 2);
            $course['class'] = array_sum(array_column($register , 'class_rate'))/$registerCount;
            $course['Attendance'] = 66;
        }
        return[
            'overCount' => $overCount,
            'stuStatus' => $stuStatus,
            'teaStatus' => $teaStatus,
            'course' => $course,
            'newStudent' => $newStudent,
        ];
    }

}