<?php
namespace backend\controllers\api;


use common\models\Major;
use Yii;
use yii\web\Controller;
use common\models\User;
use yii\web\Response;
use common\models\Department;

/**
 * Site controller
 */
class DepartmentController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionOne()
    {
        $department = new Department();
        $department->scenario = Department::SCENARIO_SEARCH_ONE;
        $department->setAttributes(Yii::$app->request->post());
        $department->expand = Yii::$app->request->post('expand');
        $department->order_by = ['id'=>2];
        return $department->getOne();
    }
    public function actionData()
    {
        $department = new Department();
        $department->scenario = Department::SCENARIO_SEARCH_ONE;
        $department->order_by = ['id'=>2];
        $department = $department->getOne();

        $user = new User();
        $user->scenario = User::SCENARIO_SEARCH;
        $user->expand = ['teacher'];
        $user->type = 2;
        $user->per_page = '';
        list($total, $user) = $user->getList();
        return[
            'number' => $department['depNo'],
            'user' => $user,
        ];
    }
    public function actionListData()
    {
        $major = new Major();
        $major->scenario = Major::SCENARIO_ADD;
        $major->order_by = ['id'=>2];
        $major =  $major->getOne();

        $majorList = new Major();
        list($total , $majorList) = $majorList->getList();

        $user = new User();
        $user->scenario = User::SCENARIO_SEARCH;
        $user->expand = ['teacher'];
        $user->type = 2;
        $user->per_page = '';
        list($total, $user) = $user->getList();
        return [
            'major'=>$majorList ,
            'numbe'=>$major ,
            'user' => $user
        ];
    }
    public function actionList()
    {
        $department = new Department();
        $department->scenario = Department::SCENARIO_LIST;
        $department->setAttributes(Yii::$app->request->post());
        $department->expand = ['user'];
        list($total, $result) = $department->getList();
        return ['data'=>$result , 'total' => $total];
    }
    public function actionEdit()
    {
        $department = new Department();
        $department->scenario = Department::SCENARIO_EDIT;
        $postData = Yii::$app->request->post();
        $department->setAttributes($this->SafeFilter($postData));
        return $department->getEdit();
    }

    public function actionAdd()
    {
        $department = new Department();
        $department->scenario = Department::SCENARIO_ADD;
        $department->setAttributes(Yii::$app->request->post());
        return $department->getAdd();
    }
}