<?php
namespace backend\controllers\api;

use Yii;
use yii\web\Controller;
use common\models\User;
use yii\web\Response;
use common\models\Major;
use common\models\Course;
use common\models\UserTeacher;
use common\models\ClassRoom;
use common\models\Register;

/**
 * Site controller
 */
class RegisterController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
    public function actionData()
    {
        $department_id = Yii::$app->request->post('department_id');
        $major = new Major();
        $major->department_id = $department_id;
        $major->per_page = '';
        list($total , $major) = $major->getList();

        $user = new UserTeacher();
        $user->department_id = $department_id;
        $user->per_page = '';
        $user->expand = ['user'];
        list($total , $user) = $user->getList();

        $course = new Course();
        $course->order_by = ['id' => 2];
        $course = $course->getOne();
        return[
            'user' => $user,
        ];
    }
    public function actionList()
    {
        $register = new Register();
        $register->scenario = Register::SCENARIO_LIST;
        $register->setAttributes(Yii::$app->request->post());
        $register->expand = ['user' , 'course'];
        list($total, $result) = $register->getList();
        if($result){
            foreach($result as &$value){
                $value['people'] = 0;
                $value['class_time'] = json_decode($value['class_time']);
            }
        }
        return ['data'=>$result , 'total' => $total];
    }
    public function actionListData()
    {
        $user = new User();
        $user->type = 2;
        $user->expand = ['teacher'];
        $user->per_page = '';
        list($totle , $teacher) = $user->getList();

        $major = new Major();
        $major->per_page = '';
        list($total, $major) = $major->getList();

        $classRoom = new ClassRoom();
        $classRoom->per_page = '';
        $classRoom->crNumberOfSeat = Yii::$app->request->post('number');
        list($total, $classRoom) = $classRoom->getList();
        return[
            'teacher' => $teacher,
            'major' => $major,
            'classRoom' => $classRoom
        ];
    }
    public function actionEdit()
    {
        $register = new Course();
        $register->scenario = Course::SCENARIO_EDIT;
        $register->setAttributes(Yii::$app->request->post());
        return $register->getEdit();
    }
    public function actionAdd()
    {
        $register = new Course();
        $register->scenario = Course::SCENARIO_ADD;
        $register->setAttributes(Yii::$app->request->post());
        return $register->getAdd();
    }
}