<?php
namespace backend\controllers\api;

use common\models\Major;
use common\models\Team;
use Yii;
use yii\web\Controller;
use common\models\User;
use yii\web\Response;

/**
 * Site controller
 */
class TeamController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionOne()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_ONE;
        $user->setAttributes(Yii::$app->request->post());
        $user->expand = Yii::$app->request->post('expand');
        $user->order_by = ['id'=>2];
        return $user->getOne();
    }
    public function actionList()
    {
        $team = new Team();
        $team->scenario = Team::SCENARIO_LIST;
        $team->setAttributes(Yii::$app->request->post());
        list($total, $result) = $team->getList();
        return ['data'=>$result , 'total' => $total];
    }
    public function actionEdit()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_EDIT;
        $postData = Yii::$app->request->post();
        $user->setAttributes($this->SafeFilter($postData));
        return $user->getEdit();
    }
    public function actionAdd()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_ADD;
        $postData = $this->SafeFilter(Yii::$app->request->post());
        $user->setAttributes($postData);
        $user->dirthday = time($user->dirthday);
        $user = $user->getAdd();
        return true;
    }
}