<?php
namespace backend\controllers\api;


use Yii;
use yii\web\Controller;
use common\models\User;
use yii\web\Response;

/**
 * Site controller
 */
class UserController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionOne()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_ADD;
        $user->id = Yii::$app->request->post('id');
        return $user->getOne();
    }
    public function actionList()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_SEARCH;
        $user->setAttributes(Yii::$app->request->post());
        list($total, $result) = $user->getList();
        return ['data'=>$result , 'total' => $total];
    }
    public function actionEdit()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_EDIT;
        $postData = Yii::$app->request->post();
        $user->setAttributes($this->SafeFilter($postData));
        return $user->getEdit();
    }
    public function actionUpdate()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_UPDATE;
        $postData = Yii::$app->request->post();
        $user->setAttributes($this->SafeFilter($postData));
        $user->id = Yii::$app->user->identity->id;
        return $user->getUpdate();
    }
    public function actionResetPassword()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_RESET_PASSWORD;
        $user->setAttributes(Yii::$app->request->post());
        $user->id = Yii::$app->user->identity->id;
        return $user->getResetPassword();
    }
    public function actionAdd()
    {
        $user = new User();
        $user->scenario = User::SCENARIO_ADD;
        $postData = Yii::$app->request->post();
        $user->setAttributes($this->SafeFilter($postData));
        $user->dirthday = time($user->dirthday);
        return $user->getAdd();

    }
}